name: CI - Build

on:
  push:
    branches: [ main ]
    paths-ignore: '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-${{ matrix.ubuntu-version }}
    strategy:
      matrix:
        ubuntu-version: [22.04]
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools build wheel

      - name: Build platform-specific wheel
        run: |
          # Build wheel
          python -m build --wheel

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-wheel-${{ matrix.ubuntu-version }}-py${{ matrix.python-version }}
          path: dist/*.whl
